/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.mycompany.views;

import com.mycompany.interfaces.DAOAsistencia;
import com.mycompany.models.Asistencias;
import com.mycompany.proyecto_gym_instructor.DAOAsistenciasImpl;
import java.awt.Color;

/**
 *
 * @author Usuario
 */
public class AgregarAsistencia extends javax.swing.JPanel {

    /**
     * Creates new form AgregarAsistencia
     */
    boolean isEdition = false;
    Asistencias edicionAsistencia;
    
    public AgregarAsistencia() {
        initComponents();
        initStyles();
    }
    
    public AgregarAsistencia(Asistencias asistencia) {
        initComponents();
        isEdition = true;
        edicionAsistencia = asistencia;
        initStyles();
    }
    
    private void initStyles(){
        jButton1.setForeground(Color.black);
        botonesArea.add(botonYoga);
        botonesArea.add(botonZumba);
        botonesArea.add(botonTrain);
        botonesHorario.add(seis_nueveAM);
        botonesHorario.add(nueve_doce);
        botonesHorario.add(doce_tres);
        botonesHorario.add(tres_seis);
        botonesHorario.add(seis_nuevePM);
        if (isEdition && edicionAsistencia != null){
            jButton1.setText("Modificar");
            jTextField1.setText(edicionAsistencia.getNombre());
            jTextField4.setText(edicionAsistencia.getFecha());
            jTextField3.setText(edicionAsistencia.getApellido());
            if (edicionAsistencia.getArea().equals("Yoga")){
                botonYoga.setSelected(true);}
            else if (edicionAsistencia.getArea().equals("Zumba")){
                botonZumba.setSelected(true);}
            else {
                botonTrain.setSelected(true);}
            if (edicionAsistencia.getHorario().equals(seis_nueveAM.getText())){
                seis_nueveAM.setSelected(true);}
            else if (edicionAsistencia.getHorario().equals(nueve_doce.getText())){
                nueve_doce.setSelected(true);}
            else if (edicionAsistencia.getHorario().equals(doce_tres.getText())){
                doce_tres.setSelected(true);}
            else if (edicionAsistencia.getHorario().equals(tres_seis.getText())){
                tres_seis.setSelected(true);}
            else {
                seis_nuevePM.setSelected(true);}
        }
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        botonesArea = new javax.swing.ButtonGroup();
        botonesHorario = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jTextField1 = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jTextField3 = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        botonYoga = new javax.swing.JRadioButton();
        botonZumba = new javax.swing.JRadioButton();
        botonTrain = new javax.swing.JRadioButton();
        jLabel8 = new javax.swing.JLabel();
        seis_nueveAM = new javax.swing.JRadioButton();
        nueve_doce = new javax.swing.JRadioButton();
        doce_tres = new javax.swing.JRadioButton();
        tres_seis = new javax.swing.JRadioButton();
        seis_nuevePM = new javax.swing.JRadioButton();
        jLabel1 = new javax.swing.JLabel();
        jTextField4 = new javax.swing.JTextField();

        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });

        jButton1.setBackground(new java.awt.Color(241, 178, 7));
        jButton1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jButton1.setText("Agregar");
        jButton1.setBorderPainted(false);
        jButton1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel2.setText("Apellido");

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel3.setText("Fecha (DD/MM/AA)");

        jLabel4.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel4.setText("Área");

        botonYoga.setText("Yoga");
        botonYoga.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonYogaActionPerformed(evt);
            }
        });

        botonZumba.setText("Zumba");

        botonTrain.setText("Entrenamiento");

        jLabel8.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel8.setText("Horario");

        seis_nueveAM.setText("6:00 AM - 8:00 AM ");
        seis_nueveAM.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                seis_nueveAMActionPerformed(evt);
            }
        });

        nueve_doce.setText("10:00 AM - 12:00 PM ");
        nueve_doce.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nueve_doceActionPerformed(evt);
            }
        });

        doce_tres.setText("12:00 PM - 2:00 PM ");
        doce_tres.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                doce_tresActionPerformed(evt);
            }
        });

        tres_seis.setText("2:00 PM - 4:00 AM ");
        tres_seis.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tres_seisActionPerformed(evt);
            }
        });

        seis_nuevePM.setText("4:00 PM - 6:00 PM ");
        seis_nuevePM.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                seis_nuevePMActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel1.setText("Nombre");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addComponent(botonYoga, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(19, 19, 19)
                .addComponent(botonZumba, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(botonTrain, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(379, 379, 379))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 223, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(78, 78, 78))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(39, 39, 39)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGap(180, 180, 180))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, 224, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 224, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(66, 66, 66)))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(seis_nueveAM, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 4, Short.MAX_VALUE)
                                .addComponent(nueve_doce)
                                .addGap(6, 6, 6)
                                .addComponent(doce_tres)
                                .addGap(8, 8, 8))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(jLabel8)
                                .addGap(165, 165, 165))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(tres_seis)
                                .addGap(36, 36, 36)
                                .addComponent(seis_nuevePM)
                                .addGap(56, 56, 56))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTextField4, javax.swing.GroupLayout.PREFERRED_SIZE, 224, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(162, 162, 162)
                .addComponent(jLabel4)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(29, 29, 29)
                        .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(18, 18, 18)
                        .addComponent(jTextField1)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(13, 13, 13)
                        .addComponent(jTextField3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(89, 89, 89)
                        .addComponent(jLabel8)
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(seis_nueveAM, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(nueve_doce)
                            .addComponent(doce_tres, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(tres_seis, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(seis_nuevePM, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addGap(15, 15, 15)
                .addComponent(jTextField4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(5, 5, 5)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(botonYoga, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(botonZumba, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(botonTrain)))
                .addGap(48, 48, 48)
                .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, 70, Short.MAX_VALUE)
                .addGap(42, 42, 42))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField1ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        String nombre = jTextField1.getText();
        String apellido = jTextField3.getText();
        String fecha = jTextField4.getText();
        String area = "";
        if (botonYoga.isSelected())
            area = botonYoga.getText();
        if (botonZumba.isSelected())
            area = botonZumba.getText();
        if (botonTrain.isSelected())
            area = botonTrain.getText();
        String horario = "";
        if (seis_nueveAM.isSelected())
            horario = seis_nueveAM.getText();
        if (nueve_doce.isSelected())
            horario = nueve_doce.getText();
        if (doce_tres.isSelected())
            horario = doce_tres.getText();
        if (tres_seis.isSelected())
            horario = tres_seis.getText();
        if (seis_nuevePM.isSelected())
            horario = seis_nuevePM.getText();


        if (nombre.isEmpty() || apellido.isEmpty() || area.isEmpty() || horario.isEmpty()){
            javax.swing.JOptionPane.showMessageDialog(this,"Debe llenar todos los campos \n", "AVISO", javax.swing.JOptionPane.ERROR_MESSAGE);
            jTextField1.requestFocus();
            return;
        }

        com.mycompany.models.Asistencias asistencia = isEdition ? edicionAsistencia : new com.mycompany.models.Asistencias();
        asistencia.setArea(area);
        asistencia.setFecha(fecha);
        asistencia.setHorario(horario);
        asistencia.setNombre(nombre);
        asistencia.setApellido(apellido);
        
        

        try{
            DAOAsistencia dao = new DAOAsistenciasImpl();
            if (!isEdition)
                dao.agregar(asistencia);
            else
                dao.modificar(asistencia);
            String mensajeExi = isEdition ? "modificado" : "registrado";
            javax.swing.JOptionPane.showMessageDialog(this,"Asistencia " + mensajeExi + " exitosamente \n", "AVISO", javax.swing.JOptionPane.INFORMATION_MESSAGE);
            
             if (!isEdition){
                jTextField1.setText("");
                jTextField3.setText("");
                jTextField4.setText("");
                botonesArea.clearSelection();
                botonesHorario.clearSelection();
            }
            
        } catch (Exception e){
            String mensajeErr = isEdition ? "modificar" : "registrar";
            javax.swing.JOptionPane.showMessageDialog(this,"Ocurrio un error al " + mensajeErr + " la asistencia \n", "AVISO", javax.swing.JOptionPane.ERROR_MESSAGE);
            System.out.println(e.getMessage());
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void botonYogaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonYogaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_botonYogaActionPerformed

    private void seis_nueveAMActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_seis_nueveAMActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_seis_nueveAMActionPerformed

    private void nueve_doceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nueve_doceActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nueve_doceActionPerformed

    private void doce_tresActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_doce_tresActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_doce_tresActionPerformed

    private void tres_seisActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tres_seisActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tres_seisActionPerformed

    private void seis_nuevePMActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_seis_nuevePMActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_seis_nuevePMActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JRadioButton botonTrain;
    private javax.swing.JRadioButton botonYoga;
    private javax.swing.JRadioButton botonZumba;
    private javax.swing.ButtonGroup botonesArea;
    private javax.swing.ButtonGroup botonesHorario;
    private javax.swing.JRadioButton doce_tres;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JRadioButton nueve_doce;
    private javax.swing.JRadioButton seis_nueveAM;
    private javax.swing.JRadioButton seis_nuevePM;
    private javax.swing.JRadioButton tres_seis;
    // End of variables declaration//GEN-END:variables
}
