/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.mycompany.views;

import com.mycompany.interfaces.DAOInscripciones;
import com.mycompany.interfaces.DAOClasesCL;
import com.mycompany.proyecto_gym_admin.DAOClasesCLImpl;
import com.mycompany.proyecto_gym_admin.DAOInscripcionesImpl;
import java.awt.Color;

/**
 *
 * @author Usuario
 */
public class InscripcionClase extends javax.swing.JPanel {

    /**
     * Creates new form InscripcionClase
     */
    
    public InscripcionClase() {
        initComponents();
        initStyles();
    }
    
    
    private void initStyles(){
        botonesArea.add(botonYoga);
        botonesArea.add(botonZumba);
        botonesArea.add(botonTrain);
        botonesHorario.add(seis_nueveAM);
        botonesHorario.add(nueve_doce);
        botonesHorario.add(doce_tres);
        botonesHorario.add(tres_seis);
        botonesHorario.add(seis_nuevePM);
        botonesDias.add(botonLunes);
        botonesDias.add(botonMartes);
        botonesDias.add(botonMiercoles);
        botonesDias.add(botonJueves);
        botonesDias.add(botonSabado);
        botonesDias.add(botonViernes);
        jButton1.setForeground(Color.black);
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        botonesDias = new javax.swing.ButtonGroup();
        botonesArea = new javax.swing.ButtonGroup();
        botonesHorario = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        nueve_doce = new javax.swing.JRadioButton();
        jButton1 = new javax.swing.JButton();
        doce_tres = new javax.swing.JRadioButton();
        tres_seis = new javax.swing.JRadioButton();
        seis_nuevePM = new javax.swing.JRadioButton();
        jLabel4 = new javax.swing.JLabel();
        botonYoga = new javax.swing.JRadioButton();
        botonZumba = new javax.swing.JRadioButton();
        botonTrain = new javax.swing.JRadioButton();
        jLabel8 = new javax.swing.JLabel();
        seis_nueveAM2 = new javax.swing.JRadioButton();
        jLabel9 = new javax.swing.JLabel();
        botonLunes = new javax.swing.JRadioButton();
        botonMartes = new javax.swing.JRadioButton();
        botonMiercoles = new javax.swing.JRadioButton();
        botonJueves = new javax.swing.JRadioButton();
        botonSabado = new javax.swing.JRadioButton();
        botonViernes = new javax.swing.JRadioButton();
        jLabel3 = new javax.swing.JLabel();
        jTextField2 = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jTextField4 = new javax.swing.JTextField();

        nueve_doce.setText("10:00 AM - 12:00 PM ");
        nueve_doce.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nueve_doceActionPerformed(evt);
            }
        });

        jButton1.setBackground(new java.awt.Color(241, 178, 7));
        jButton1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jButton1.setText("Inscribirse");
        jButton1.setBorderPainted(false);
        jButton1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        doce_tres.setText("12:00 PM - 2:00 PM ");
        doce_tres.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                doce_tresActionPerformed(evt);
            }
        });

        tres_seis.setText("2:00 PM - 4:00 AM ");
        tres_seis.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tres_seisActionPerformed(evt);
            }
        });

        seis_nuevePM.setText("4:00 PM - 6:00 PM ");
        seis_nuevePM.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                seis_nuevePMActionPerformed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel4.setText("Área");

        botonYoga.setText("Yoga");
        botonYoga.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonYogaActionPerformed(evt);
            }
        });

        botonZumba.setText("Zumba");

        botonTrain.setText("Entrenamiento");

        jLabel8.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel8.setText("Horario");

        seis_nueveAM2.setText("6:00 AM - 8:00 AM ");
        seis_nueveAM2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                seis_nueveAM2ActionPerformed(evt);
            }
        });

        jLabel9.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel9.setText("Día");

        botonLunes.setText("Lunes");
        botonLunes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonLunesActionPerformed(evt);
            }
        });

        botonMartes.setText("Martes");
        botonMartes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonMartesActionPerformed(evt);
            }
        });

        botonMiercoles.setText("Miércoles");
        botonMiercoles.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonMiercolesActionPerformed(evt);
            }
        });

        botonJueves.setText("Jueves");
        botonJueves.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonJuevesActionPerformed(evt);
            }
        });

        botonSabado.setText("Sábado");
        botonSabado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonSabadoActionPerformed(evt);
            }
        });

        botonViernes.setText("Viernes");
        botonViernes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonViernesActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel3.setText("ID");

        jTextField2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField2ActionPerformed(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel5.setText("Instructor");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(39, 39, 39)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, 224, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3)
                    .addComponent(jTextField4, javax.swing.GroupLayout.PREFERRED_SIZE, 224, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel4)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(botonYoga)
                                .addGap(18, 18, 18)
                                .addComponent(botonZumba)))
                        .addGap(18, 18, 18)
                        .addComponent(botonTrain)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 47, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 223, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(65, 65, 65))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                    .addComponent(botonJueves)
                                    .addGap(37, 37, 37)
                                    .addComponent(botonViernes)
                                    .addGap(34, 34, 34)
                                    .addComponent(botonSabado)
                                    .addGap(61, 61, 61))
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                    .addComponent(seis_nueveAM2, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(nueve_doce)
                                    .addGap(6, 6, 6)
                                    .addComponent(doce_tres))
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                    .addComponent(jLabel8)
                                    .addGap(157, 157, 157))
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                    .addComponent(tres_seis)
                                    .addGap(36, 36, 36)
                                    .addComponent(seis_nuevePM)
                                    .addGap(48, 48, 48)))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel9)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(botonLunes, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(botonMartes)))
                                .addGap(18, 18, 18)
                                .addComponent(botonMiercoles)
                                .addGap(78, 78, 78)))
                        .addContainerGap())))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(66, 66, 66)
                .addComponent(jLabel9)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(botonLunes, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(botonMartes)
                    .addComponent(botonMiercoles, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(botonSabado)
                    .addComponent(botonJueves, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(botonViernes, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addComponent(jLabel8)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(seis_nueveAM2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(nueve_doce)
                    .addComponent(doce_tres, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tres_seis, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(seis_nuevePM, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(86, 86, 86)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(45, 45, 45))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(65, 65, 65)
                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTextField4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(botonYoga, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(botonZumba, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(botonTrain))
                .addGap(166, 166, 166))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void nueve_doceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nueve_doceActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nueve_doceActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        String id = jTextField2.getText();
        int ID = Integer.parseInt(id);
        String instructor = jTextField4.getText();
        String area = "";
        if (botonYoga.isSelected())
            area = botonYoga.getText();
        if (botonZumba.isSelected())
            area = botonZumba.getText();
        if (botonTrain.isSelected())
            area = botonTrain.getText();
        String dia = "";
        if (botonLunes.isSelected())
            dia = botonLunes.getText();
        if (botonMartes.isSelected())
            dia = botonMartes.getText();
        if (botonMiercoles.isSelected())
            dia = botonMiercoles.getText();
        if (botonJueves.isSelected())
            dia = botonJueves.getText();
        if (botonViernes.isSelected())
            dia = botonViernes.getText();
        if (botonSabado.isSelected())
            dia = botonSabado.getText();
        String horario = "";
        if (seis_nueveAM2.isSelected())
            horario = seis_nueveAM2.getText();
        if (nueve_doce.isSelected())
            horario = nueve_doce.getText();
        if (doce_tres.isSelected())
            horario = doce_tres.getText();
        if (tres_seis.isSelected())
            horario = tres_seis.getText();
        if (seis_nuevePM.isSelected())
            horario = seis_nuevePM.getText();

        if (id.isEmpty() || horario.isEmpty() || area.isEmpty() || instructor.isEmpty()){
            javax.swing.JOptionPane.showMessageDialog(this,"Debe llenar todos los campos \n", "AVISO", javax.swing.JOptionPane.ERROR_MESSAGE);
            jTextField2.requestFocus();
            return;
        }

        com.mycompany.models.Inscripciones inscripcion = new com.mycompany.models.Inscripciones();
        inscripcion.setID(ID);
        inscripcion.setDia(dia);
        inscripcion.setHorario(horario);
        inscripcion.setArea(area);
        inscripcion.setInstructor(instructor);
        
        
        
        try{
            DAOClasesCL dao1 = new DAOClasesCLImpl();
            DAOInscripciones dao = new DAOInscripcionesImpl();
            dao.inscripcion(dao1.obtenerClasePorID(inscripcion.getID()),inscripcion);
            javax.swing.JOptionPane.showMessageDialog(this,"Inscripcion registrada exitosamente \n", "AVISO", javax.swing.JOptionPane.INFORMATION_MESSAGE);

            jTextField2.setText("");
            jTextField4.setText("");
            botonesDias.clearSelection();
            botonesArea.clearSelection();
            botonesHorario.clearSelection();

        } catch (Exception e){
            javax.swing.JOptionPane.showMessageDialog(this,"Ocurrio un error al registrar la inscripcion \n", "AVISO", javax.swing.JOptionPane.ERROR_MESSAGE);
            System.out.println(e.getMessage());
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void doce_tresActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_doce_tresActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_doce_tresActionPerformed

    private void tres_seisActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tres_seisActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tres_seisActionPerformed

    private void seis_nuevePMActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_seis_nuevePMActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_seis_nuevePMActionPerformed

    private void botonYogaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonYogaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_botonYogaActionPerformed

    private void seis_nueveAM2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_seis_nueveAM2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_seis_nueveAM2ActionPerformed

    private void botonLunesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonLunesActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_botonLunesActionPerformed

    private void botonMartesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonMartesActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_botonMartesActionPerformed

    private void botonMiercolesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonMiercolesActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_botonMiercolesActionPerformed

    private void botonJuevesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonJuevesActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_botonJuevesActionPerformed

    private void botonSabadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonSabadoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_botonSabadoActionPerformed

    private void botonViernesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonViernesActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_botonViernesActionPerformed

    private void jTextField2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField2ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JRadioButton botonJueves;
    private javax.swing.JRadioButton botonLunes;
    private javax.swing.JRadioButton botonMartes;
    private javax.swing.JRadioButton botonMiercoles;
    private javax.swing.JRadioButton botonSabado;
    private javax.swing.JRadioButton botonTrain;
    private javax.swing.JRadioButton botonViernes;
    private javax.swing.JRadioButton botonYoga;
    private javax.swing.JRadioButton botonZumba;
    private javax.swing.ButtonGroup botonesArea;
    private javax.swing.ButtonGroup botonesDias;
    private javax.swing.ButtonGroup botonesHorario;
    private javax.swing.JRadioButton doce_tres;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JRadioButton nueve_doce;
    private javax.swing.JRadioButton seis_nueveAM;
    private javax.swing.JRadioButton seis_nueveAM1;
    private javax.swing.JRadioButton seis_nueveAM2;
    private javax.swing.JRadioButton seis_nuevePM;
    private javax.swing.JRadioButton tres_seis;
    // End of variables declaration//GEN-END:variables
}
