/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.mycompany.views;

import com.mycompany.interfaces.DAOClasesAdmin;
import com.mycompany.proyecto_gym_poo.DAOClasesAdminImpl;
import java.awt.Color;

/**
 *
 * @author Usuario
 */
public class ModificarClase extends javax.swing.JPanel {

    com.mycompany.models.ClasesAdmin claseEdit;
    
    /**
     * Creates new form ModificarClase
     * @param clase
     */
    public ModificarClase(com.mycompany.models.ClasesAdmin clase) {
        initComponents();
        claseEdit = clase;
        initStyles();
    }

    private void initStyles(){
        botonesArea.add(botonYoga);
        botonesArea.add(botonZumba);
        botonesArea.add(botonTrain);
        botonesHorario.add(seis_nueveAM);
        botonesHorario.add(nueve_doce);
        botonesHorario.add(doce_tres);
        botonesHorario.add(tres_seis);
        botonesHorario.add(seis_nuevePM);
        botonesHorario.add(nueve_once);
        jButton1.setForeground(Color.black);
        jTextField1.setText(claseEdit.getInstructor());
        boolean state = claseEdit.isEstado();
        String estado = Boolean.toString(state);
        jTextField2.setText(estado);
        if ("Yoga".equals(claseEdit.getArea())){
            botonYoga.setSelected(true);}
        else if ("Zumba".equals(claseEdit.getArea())){
            botonZumba.setSelected(true);}
        else {
            botonTrain.setSelected(true);}
            
            
        if (claseEdit.getHorario().equals(seis_nueveAM.getText())){
            seis_nueveAM.setSelected(true);}
        else if (claseEdit.getHorario().equals(nueve_doce.getText())){
            nueve_doce.setSelected(true);}
        else if (claseEdit.getHorario().equals(doce_tres.getText())){
            doce_tres.setSelected(true);}
        else if (claseEdit.getHorario().equals(tres_seis.getText())){
            tres_seis.setSelected(true);}
        else if (claseEdit.getHorario().equals(seis_nuevePM.getText())){
            seis_nuevePM.setSelected(true);}
        else {
            nueve_once.setSelected(true);
            }
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        botonesArea = new javax.swing.ButtonGroup();
        botonesHorario = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        botonYoga = new javax.swing.JRadioButton();
        botonZumba = new javax.swing.JRadioButton();
        botonTrain = new javax.swing.JRadioButton();
        seis_nueveAM = new javax.swing.JRadioButton();
        nueve_doce = new javax.swing.JRadioButton();
        doce_tres = new javax.swing.JRadioButton();
        tres_seis = new javax.swing.JRadioButton();
        seis_nuevePM = new javax.swing.JRadioButton();
        nueve_once = new javax.swing.JRadioButton();
        jLabel6 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jTextField2 = new javax.swing.JTextField();
        jTextField5 = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel1.setText("Instructor");

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel3.setText("Estado");

        jLabel4.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel4.setText("Área");

        botonYoga.setText("Yoga");
        botonYoga.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonYogaActionPerformed(evt);
            }
        });

        botonZumba.setText("Zumba");

        botonTrain.setText("Entrenamiento");

        seis_nueveAM.setText("6:00 AM - 9:00 AM ");
        seis_nueveAM.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                seis_nueveAMActionPerformed(evt);
            }
        });

        nueve_doce.setText("9:00 AM - 12:00 PM ");
        nueve_doce.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nueve_doceActionPerformed(evt);
            }
        });

        doce_tres.setText("12:00 PM - 3:00 PM ");
        doce_tres.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                doce_tresActionPerformed(evt);
            }
        });

        tres_seis.setText("3:00 PM - 6:00 AM ");
        tres_seis.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tres_seisActionPerformed(evt);
            }
        });

        seis_nuevePM.setText("6:00 PM - 9:00 PM ");
        seis_nuevePM.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                seis_nuevePMActionPerformed(evt);
            }
        });

        nueve_once.setText("9:00 PM - 11:00 PM ");
        nueve_once.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nueve_onceActionPerformed(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel6.setText("Cupos");

        jButton1.setBackground(new java.awt.Color(241, 178, 7));
        jButton1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jButton1.setText("Modificar");
        jButton1.setBorderPainted(false);
        jButton1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel8.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel8.setText("Horario");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(39, 39, 39)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jTextField5)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 81, Short.MAX_VALUE)
                        .addGap(157, 157, 157))
                    .addComponent(jTextField2)
                    .addComponent(jTextField1)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(135, 135, 135)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(botonYoga)
                                .addGap(18, 18, 18)
                                .addComponent(botonZumba))
                            .addComponent(jLabel8))
                        .addGap(18, 18, 18)
                        .addComponent(botonTrain, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(9, 9, 9))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(101, 101, 101)
                        .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, 278, Short.MAX_VALUE)
                        .addGap(94, 94, 94))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(tres_seis)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(nueve_once))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addComponent(seis_nueveAM, javax.swing.GroupLayout.DEFAULT_SIZE, 149, Short.MAX_VALUE)
                                .addGap(18, 18, 18)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(seis_nuevePM)
                                        .addGap(0, 0, Short.MAX_VALUE))
                                    .addComponent(nueve_doce, javax.swing.GroupLayout.DEFAULT_SIZE, 158, Short.MAX_VALUE))
                                .addGap(11, 11, 11)
                                .addComponent(doce_tres)))
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel4)
                        .addGap(211, 211, 211))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(29, 29, 29)
                        .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextField1))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(23, 23, 23)
                        .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(botonYoga, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(botonZumba, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(botonTrain, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(117, 117, 117)
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextField5, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(77, 77, 77))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(80, 80, 80)
                        .addComponent(jLabel8)
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(seis_nueveAM, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(nueve_doce)
                            .addComponent(doce_tres, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(tres_seis, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(seis_nuevePM, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(nueve_once))
                        .addGap(76, 76, 76)
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 46, Short.MAX_VALUE))))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void botonYogaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonYogaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_botonYogaActionPerformed

    private void nueve_doceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nueve_doceActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nueve_doceActionPerformed

    private void doce_tresActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_doce_tresActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_doce_tresActionPerformed

    private void tres_seisActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tres_seisActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tres_seisActionPerformed

    private void nueve_onceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nueve_onceActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nueve_onceActionPerformed

    private void seis_nuevePMActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_seis_nuevePMActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_seis_nuevePMActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        String instructor = jTextField1.getText();
        String state = jTextField2.getText();
        boolean estado = Boolean.parseBoolean(state);
        String cup = jTextField5.getText();
        int cupos = Integer.parseInt(cup);
        String area = "";
        if (botonYoga.isSelected())
            area = botonYoga.getText();
        if (botonZumba.isSelected())
            area = botonZumba.getText();
        if (botonTrain.isSelected())
            area = botonTrain.getText();

        String horario = "";
        if (seis_nueveAM.isSelected())
            horario = seis_nueveAM.getText();
        if (nueve_doce.isSelected())
            horario = nueve_doce.getText();
        if (doce_tres.isSelected())
            horario = doce_tres.getText();
        if (tres_seis.isSelected())
            horario = tres_seis.getText();
        if (seis_nuevePM.isSelected())
            horario = seis_nuevePM.getText();
        if (nueve_once.isSelected())
            horario = nueve_once.getText();
        
        
        if (instructor.isEmpty() || area.isEmpty() || horario.isEmpty() || cup.isEmpty() || state.isEmpty()){
            javax.swing.JOptionPane.showMessageDialog(this,"Debe llenar todos los campos \n", "AVISO", javax.swing.JOptionPane.ERROR_MESSAGE);
            jTextField1.requestFocus();
            return;
        }
        
        
        com.mycompany.models.ClasesAdmin clase = claseEdit;
        clase.setInstructor(instructor);
        clase.setEstado(estado);
        clase.setCupos(cupos);
        clase.setArea(area);
        clase.setHorario(horario);
        
        try{
            DAOClasesAdmin dao = new DAOClasesAdminImpl();
            dao.modificar(clase);
            javax.swing.JOptionPane.showMessageDialog(this,"Clase modificada exitosamente \n", "AVISO", javax.swing.JOptionPane.INFORMATION_MESSAGE);
            
        } catch (Exception e){
            javax.swing.JOptionPane.showMessageDialog(this,"Ocurrio un error al modificar la clase \n", "AVISO", javax.swing.JOptionPane.ERROR_MESSAGE);
            System.out.println(e.getMessage());
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void seis_nueveAMActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_seis_nueveAMActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_seis_nueveAMActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JRadioButton botonTrain;
    private javax.swing.JRadioButton botonYoga;
    private javax.swing.JRadioButton botonZumba;
    private javax.swing.ButtonGroup botonesArea;
    private javax.swing.ButtonGroup botonesHorario;
    private javax.swing.JRadioButton doce_tres;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField5;
    private javax.swing.JRadioButton nueve_doce;
    private javax.swing.JRadioButton nueve_once;
    private javax.swing.JRadioButton seis_nueveAM;
    private javax.swing.JRadioButton seis_nuevePM;
    private javax.swing.JRadioButton tres_seis;
    // End of variables declaration//GEN-END:variables
}
