/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.mycompany.views;

import com.mycompany.interfaces.DAOMiembros;
import com.mycompany.proyecto_gym_poo.DAOMiembrosImpl;
import java.awt.Color;

/**
 *
 * @author Usuario
 */
public class RegistroMiembro extends javax.swing.JPanel {

    /**
     * Creates new form RegistroMiembro
     */
    boolean isEdition = false;
    com.mycompany.models.Miembros edicionMiembro;
    
    public RegistroMiembro() {
        initComponents();
        initStyles();
    }
    
    public RegistroMiembro(com.mycompany.models.Miembros usuario) {
        initComponents();
        isEdition = true;
        edicionMiembro = usuario;
        initStyles();
    }
    
    
    private void initStyles(){
        jButton1.setForeground(Color.black);
        botones.add(botonPlatino);
        botones.add(botonOro);
        botones.add(botonBronce);
        botonesHorario.add(seis_nueveAM);
        botonesHorario.add(nueve_doce);
        botonesHorario.add(doce_tres);
        botonesHorario.add(tres_seis);
        botonesHorario.add(seis_nuevePM);
        botonesHorario.add(nueve_once);
        if (isEdition && edicionMiembro != null){
            jButton1.setText("Modificar");
            jTextField1.setText(edicionMiembro.getNombre());
            jTextField3.setText(edicionMiembro.getApellido());
            jTextField2.setText(edicionMiembro.getDocumento());
            jTextField4.setText(edicionMiembro.getTelefono());
            jTextField5.setText(edicionMiembro.getCorreo());
            jTextField1.setText(edicionMiembro.getNombre());
            if (edicionMiembro.getMemb_area().equals("Platino")){
                botonPlatino.setSelected(true);}
            else if (edicionMiembro.getMemb_area().equals("Oro")){
                botonOro.setSelected(true);}
            else {
                botonBronce.setSelected(true);}
            if (edicionMiembro.getHorario().equals(seis_nueveAM.getText())){
                seis_nueveAM.setSelected(true);}
            else if (edicionMiembro.getHorario().equals(nueve_doce.getText())){
                nueve_doce.setSelected(true);}
            else if (edicionMiembro.getHorario().equals(doce_tres.getText())){
                doce_tres.setSelected(true);}
            else if (edicionMiembro.getHorario().equals(tres_seis.getText())){
                tres_seis.setSelected(true);}
            else if (edicionMiembro.getHorario().equals(seis_nuevePM.getText())){
                seis_nuevePM.setSelected(true);}
            else {
                nueve_once.setSelected(true);
            }
        }
        }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        botones = new javax.swing.ButtonGroup();
        botonesHorario = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        botonPlatino = new javax.swing.JRadioButton();
        botonOro = new javax.swing.JRadioButton();
        botonBronce = new javax.swing.JRadioButton();
        jLabel6 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jTextField2 = new javax.swing.JTextField();
        jTextField3 = new javax.swing.JTextField();
        jTextField4 = new javax.swing.JTextField();
        jTextField5 = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        seis_nueveAM = new javax.swing.JRadioButton();
        nueve_doce = new javax.swing.JRadioButton();
        doce_tres = new javax.swing.JRadioButton();
        tres_seis = new javax.swing.JRadioButton();
        nueve_once = new javax.swing.JRadioButton();
        seis_nuevePM = new javax.swing.JRadioButton();

        setPreferredSize(new java.awt.Dimension(750, 455));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel1.setText("Nombre");

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel2.setText("Apellido");

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel3.setText("Documento");

        jLabel4.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel4.setText("Membresía");

        jLabel5.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel5.setText("Número telefónico");

        botonPlatino.setText("Platino");
        botonPlatino.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonPlatinoActionPerformed(evt);
            }
        });

        botonOro.setText("Oro");

        botonBronce.setText("Bronce");

        jLabel6.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel6.setText("Correo electrónico");

        jButton1.setBackground(new java.awt.Color(241, 178, 7));
        jButton1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jButton1.setText("Registrar");
        jButton1.setBorderPainted(false);
        jButton1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel8.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel8.setText("Horario");

        seis_nueveAM.setText("6:00 AM - 9:00 AM ");
        seis_nueveAM.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                seis_nueveAMActionPerformed(evt);
            }
        });

        nueve_doce.setText("9:00 AM - 12:00 PM ");
        nueve_doce.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nueve_doceActionPerformed(evt);
            }
        });

        doce_tres.setText("12:00 PM - 3:00 PM ");
        doce_tres.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                doce_tresActionPerformed(evt);
            }
        });

        tres_seis.setText("3:00 PM - 6:00 AM ");
        tres_seis.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tres_seisActionPerformed(evt);
            }
        });

        nueve_once.setText("9:00 PM - 11:00 PM ");
        nueve_once.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nueve_onceActionPerformed(evt);
            }
        });

        seis_nuevePM.setText("6:00 PM - 9:00 PM ");
        seis_nuevePM.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                seis_nuevePMActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(39, 39, 39)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(botonPlatino, javax.swing.GroupLayout.DEFAULT_SIZE, 67, Short.MAX_VALUE)
                        .addGap(18, 18, 18)
                        .addComponent(botonOro, javax.swing.GroupLayout.DEFAULT_SIZE, 49, Short.MAX_VALUE)
                        .addGap(18, 18, 18)
                        .addComponent(botonBronce, javax.swing.GroupLayout.DEFAULT_SIZE, 67, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(94, 94, 94))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(135, 135, 135))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(158, 158, 158))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(95, 95, 95))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(139, 139, 139))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(157, 157, 157))
                    .addComponent(jTextField4)
                    .addComponent(jTextField2)
                    .addComponent(jTextField3)
                    .addComponent(jTextField1)
                    .addComponent(jTextField5))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(101, 101, 101)
                        .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(94, 94, 94))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(31, 31, 31)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(tres_seis)
                                .addGap(18, 18, 18)
                                .addComponent(seis_nuevePM)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(nueve_once))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(seis_nueveAM, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addGap(18, 18, 18)
                                        .addComponent(nueve_doce, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                        .addGap(0, 0, Short.MAX_VALUE)
                                        .addComponent(jLabel8)
                                        .addGap(37, 37, 37)))
                                .addGap(11, 11, 11)
                                .addComponent(doce_tres)))
                        .addContainerGap(47, Short.MAX_VALUE))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 26, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextField1, javax.swing.GroupLayout.DEFAULT_SIZE, 27, Short.MAX_VALUE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, 25, Short.MAX_VALUE)
                        .addGap(13, 13, 13)
                        .addComponent(jTextField3, javax.swing.GroupLayout.DEFAULT_SIZE, 27, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel8, javax.swing.GroupLayout.DEFAULT_SIZE, 24, Short.MAX_VALUE)
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(seis_nueveAM, javax.swing.GroupLayout.DEFAULT_SIZE, 28, Short.MAX_VALUE)
                            .addComponent(nueve_doce)
                            .addComponent(doce_tres, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(tres_seis, javax.swing.GroupLayout.DEFAULT_SIZE, 29, Short.MAX_VALUE)
                            .addComponent(seis_nuevePM, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(nueve_once))
                        .addGap(60, 60, 60)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTextField2)
                .addGap(10, 10, 10)
                .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(botonPlatino, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(botonOro, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(botonBronce, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(8, 8, 8)
                .addComponent(jTextField4, javax.swing.GroupLayout.DEFAULT_SIZE, 23, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, 21, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jTextField5, javax.swing.GroupLayout.DEFAULT_SIZE, 23, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(4, 4, 4)
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addGap(33, 33, 33))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void botonPlatinoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonPlatinoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_botonPlatinoActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        String nombre = jTextField1.getText();
        String apellido = jTextField3.getText();
        String documento = jTextField2.getText();
        String membresia = "";
        if (botonPlatino.isSelected())
            membresia = botonPlatino.getText();
        if (botonOro.isSelected())
            membresia = botonOro.getText();
        if (botonBronce.isSelected())
            membresia = botonBronce.getText();
        String telefono = jTextField4.getText();
        String correo = jTextField5.getText();
        String horario = "";
        if (seis_nueveAM.isSelected())
            horario = seis_nueveAM.getText();
        if (nueve_doce.isSelected())
            horario = nueve_doce.getText();
        if (doce_tres.isSelected())
            horario = doce_tres.getText();
        if (tres_seis.isSelected())
            horario = tres_seis.getText();
        if (seis_nuevePM.isSelected())
            horario = seis_nuevePM.getText();
        if (nueve_once.isSelected())
            horario = nueve_once.getText();
        
        if (nombre.isEmpty() || apellido.isEmpty() || documento.isEmpty() || membresia.isEmpty() || telefono.isEmpty() || correo.isEmpty() || horario.isEmpty()){
            javax.swing.JOptionPane.showMessageDialog(this,"Debe llenar todos los campos \n", "AVISO", javax.swing.JOptionPane.ERROR_MESSAGE);
            jTextField1.requestFocus();
            return;
        }
        
        
        com.mycompany.models.Miembros user = isEdition ? edicionMiembro : new com.mycompany.models.Miembros();
        user.setNombre(nombre);
        user.setApellido(apellido);
        user.setDocumento(documento);
        user.setMemb_area(membresia);
        user.setTelefono(telefono);
        user.setCorreo(correo);
        user.setHorario(horario);
        user.setPago(true);
        
        try{
            DAOMiembros dao = new DAOMiembrosImpl();
            if (!isEdition)
                dao.registrar(user);
            else
                dao.modificar(user);
            String mensajeExi = isEdition ? "modificado" : "registrado";
            javax.swing.JOptionPane.showMessageDialog(this,"Usuario " +  mensajeExi + " exitosamente \n", "AVISO", javax.swing.JOptionPane.INFORMATION_MESSAGE);
            
            if (!isEdition){
                jTextField1.setText("");
                jTextField3.setText("");
                jTextField2.setText("");
                botones.clearSelection();
                jTextField4.setText("");
                jTextField5.setText("");
                botonesHorario.clearSelection();
            }
            
        } catch (Exception e){
            String mensajeErr = isEdition ? "modificar" : "registrar";
            javax.swing.JOptionPane.showMessageDialog(this,"Ocurrio un error al " + mensajeErr + " el usuario \n", "AVISO", javax.swing.JOptionPane.ERROR_MESSAGE);
            System.out.println(e.getMessage());
        }
      
    }//GEN-LAST:event_jButton1ActionPerformed

    private void seis_nueveAMActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_seis_nueveAMActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_seis_nueveAMActionPerformed

    private void nueve_doceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nueve_doceActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nueve_doceActionPerformed

    private void doce_tresActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_doce_tresActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_doce_tresActionPerformed

    private void tres_seisActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tres_seisActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tres_seisActionPerformed

    private void nueve_onceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nueve_onceActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nueve_onceActionPerformed

    private void seis_nuevePMActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_seis_nuevePMActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_seis_nuevePMActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JRadioButton botonBronce;
    private javax.swing.JRadioButton botonOro;
    private javax.swing.JRadioButton botonPlatino;
    private javax.swing.ButtonGroup botones;
    private javax.swing.ButtonGroup botonesHorario;
    private javax.swing.JRadioButton doce_tres;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JTextField jTextField5;
    private javax.swing.JRadioButton nueve_doce;
    private javax.swing.JRadioButton nueve_once;
    private javax.swing.JRadioButton seis_nueveAM;
    private javax.swing.JRadioButton seis_nuevePM;
    private javax.swing.JRadioButton tres_seis;
    // End of variables declaration//GEN-END:variables
}
